name: A workflow for my Hello World file
on: [workflow_dispatch]
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Nakujh" 
  continue:  
    name: Send mail
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-send-mail@v2
        with:
             server_address: smtp.gmail.com
             server_port: 465
             username: ${{secrets.MAIL_USERNAME}}
             password: ${{secrets.MAIL_PASSWORD}}
             subject: Github Actions job result
             # Literal body:
             body: Build job of ${{github.repository}} completed successfully!
             # Read file contents as body:
             # body: file://README.md
             to: jhanarendra96@gmail.com,nj185051@ncr.com
             #nj185051@ncr.com
             from: Runner
             # Optional content type (defaults to text/plain):
             content_type: text/html
             # Optional attachments:
             # attachments: attachments.zip,git.diff,./dist/static/main.js
