name: Python package

on: 
  workflow_dispatch:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
#on: [pull_request,workflow_dispatch]
  #push:
    #branches: [ master ]
  #pull_request:
    #branches: [  master ]
  #workflow_dispatch:
    #branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: | 
        python -m pip install --upgrade pip
        pip install python-docx
    - name: Append Line
      env: 
        API_USER: ${{secrets.API_USER}} 
        RELEASE_USER: ${{ github.actor }}
      run: |
        cd LineAppender
        python Build/AppendLine.py
        cd ..
        cd DocumentMaker
        python DocumentMaker.py
    - name: update file and push to remote
      #uses: actions/checkout@v2
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add *.dpr
        git commit -m "Update"
        git push origin 
      #HEAD:$GITHUB_REF
